module Site24x7client
  class LocationProfile < BaseModel
    [
      :profile_name,         # string  Mandatory Display name for the location profile.
      :primary_location,     # string  Mandatory Primary location for monitoring.
      :secondary_locations,  # array Secondary location for monitoring
      :profile_id,           # string  Unique ID generated by the server. This can be used as an identifier.
      :profile_name,         # string  Display name for the location profile.
      :primary_location,     # string  Primary location for monitoring.
      :secondary_locations   # array Secondary location for monitoring
  ].each do |key|
      attribute(key)
    end
  end
end
