module Site24x7client
  class UserGroup < BaseModel
    [
      :display_name,  # string  Mandatory Display name for the user group.
      :users,         # array Mandatory User IDs of the users to be associated to the group.
      :user_group_id  # string  Unique ID generated by the server. This can be used as an identifier.
    ].each do |key|
      attribute(key)
    end
  end
end